"""add phone number

Revision ID: f0c4ec39db31
Revises: 9b46a08d05fa
Create Date: 2025-05-18 08:34:02.562189

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f0c4ec39db31'
down_revision: Union[str, None] = '9b46a08d05fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('all_users', sa.Column('phone_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('all_users', 'phone_number')
    # ### end Alembic commands ###
